### ISSUE TITLE
Typelib not installed

### ISSUE THREAD

**Issue by alcantara09** [doudou/rock_website#1]
After creating the bundle and in the first run from Syskit in "Bundles and bundles' file structure" 
the command 

$ syskit run 

fail and produces the following error message is 

*Cannot require 'typelib'                                                                               
If you are using Rock, the 'typelib' package should have been installed automatically.                 
First, make sure that you have loaded autoproj's env.sh script before continuing                       
Second, typelib should be installed in tools/typelib from the root of your Rock installation.          
If it is not the case, report this to the rock developers. To workaround, run                          
  amake typelib                                                                                        
and try again.*

**Comment by doudou** [comment]
Thanks. This should be fixed in the upcoming autoproj 2.1. I leave this issue open until it is released so that we don't forget to check
